### ISSUE TITLE
Version lwjgl

### ISSUE THREAD

**Issue by squid233** [Funny-Developers/MvZJE#1]
2 or 3?

**Comment by crazy-piggy** [comment]
I don't konw
I'll use Java 16

**Comment by crazy-piggy** [comment]
lwjgl3
I may start this project after I leave school this afternoon
import org.lwjgl.*;[doge]

**Comment by squid233** [comment]
please lwjgl 3 and **java 17**

**Comment by crazy-piggy** [comment]
okok
please help me to new the project and upload to here

**Comment by crazy-piggy** [comment]
closed
